name: Neoload Test

on:
  push:
    branches:
      - main

jobs:
  neoload_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Neoload CLI
        run: pip3 install -U neoload
        
      - name: Extract Neoload test project
        run: unzip demowebshopp.zip -d demowebshopp
      
      - name: Run Neoload help
        run: neoload run --help 
        
      - name: Run Neoload test
        run: neoload run --scenario 'HappyFlow'
        
      - name: "Generate Test Report"
        run: neoload test-results junitsla

      - name: "Publish Test Report"
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: junit-sla.xml
          fail_on_test_failures: true
