name: Neoload Test

on:
  push:
    branches:
      - main

jobs:
  neoload_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Neoload CLI
        run: pip3 install -U neoload

      - name: Log in to Neoload Web
        run: neoload login

      - name: Extract Neoload test project
        run: |
          mkdir -p tests/neoload_projects
          unzip demowebshopp.zip -d tests/neoload_projects

      - name: Run Neoload test
        run: neoload run --scenario "HappyFlow" --detached "My Github Test With CLI"

      - name: Check Neoload test status
        run: |
          status=$(neoload status)
          if [[ $status == *"No active test found"* ]]; then
            echo "Neoload test run completed successfully"
          else
            echo "Neoload test run failed"
            exit 1
          fi
