name: Neoload Test

on:
  push:
    branches:
      - main

jobs:
  neoload_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Neoload CLI
        run: pip3 install -U neoload
                  
      - name: Extract Neoload test project
        run: |
          mkdir -p tests/neoload_projects
          unzip -o demowebshopp.zip -d tests/neoload_projects
      
      - name: Run Neoload test
        run: |
          neoload run --scenario "HappyFlow" "My Github Test With CLI"
          status=$?
          if [ $status -eq 0 ]; then
            echo "Neoload test run completed successfully"
          else
            echo "Neoload test run failed with exit code $status"
            exit 1
          fi
        
      - name: Generate Test Report
        run: neoload test-results junitsla

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: junit-sla.xml
          fail_on_test_failures: true
